package com.thedesitadka.provider.plugins

import com.thedesitadka.core.model.Category

object PrmoviesMenuCategories {

    private val CHURCH_CATEGORIES = listOf(
        Category(id = "dual-audio", name = "Dual Audio", url = "https://prmovies.church/genre/dual-audio/"),
        Category(id = "2026", name = "New Movies", url = "https://prmovies.church/release-year/2026/"),
        Category(id = "top-rated", name = "Trending", url = "https://prmovies.church/genre/top-rated/"),
        Category(id = "hollywood-dubbed", name = "Hollywood Dubbed", url = "https://prmovies.church/genre/hollywood-dubbed/"),
        Category(id = "south-special", name = "South Dubbed", url = "https://prmovies.church/genre/south-special/"),
        Category(id = "unofficial-dubbed", name = "Unofficial Hindi Dubbed", url = "https://hhdmovies.church/genre/unofficial-dubbed/"),
        Category(id = "bollywood", name = "Bollywood", url = "https://prmovies.church/genre/bollywood/"),
        Category(id = "church_cat_8", name = "Bollywood (2026)", url = "https://prmovies.church/account/?ptype=post&tax_category%5B%5D=bollywood&tax_release-year=2026&wpas=1"),
        Category(id = "church_cat_9", name = "Bollywood (2025)", url = "https://prmovies.church/account/?ptype=post&tax_category%5B%5D=bollywood&tax_release-year=2025&wpas=1"),
        Category(id = "church_cat_10", name = "Bollywood (2024)", url = "https://prmovies.church/account/?ptype=post&tax_category%5B%5D=bollywood&tax_release-year=2024&wpas=1"),
        Category(id = "hollywood", name = "Hollywood", url = "https://prmovies.church/genre/hollywood/"),
        Category(id = "church_cat_12", name = "Hollywood (2026)", url = "https://prmovies.church/account/?ptype=post&tax_category%5B%5D=hollywood&tax_release-year=2026&wpas=1"),
        Category(id = "church_cat_13", name = "Hollywood (2025)", url = "https://prmovies.church/account/?ptype=post&tax_category%5B%5D=hollywood&tax_release-year=2025&wpas=1"),
        Category(id = "church_cat_14", name = "Hollywood (2024)", url = "https://prmovies.church/account/?ptype=post&tax_category%5B%5D=hollywood&tax_release-year=2024&wpas=1"),
        Category(id = "series", name = "English Series", url = "https://prmovies.church/series/"),
        Category(id = "web-series", name = "Hindi Series", url = "https://prmovies.church/genre/web-series/"),
        Category(id = "netflix", name = "Netflix", url = "https://prmovies.church/director/netflix/"),
        Category(id = "amazon-prime", name = "Amazon", url = "https://prmovies.church/director/amazon-prime/"),
        Category(id = "altbalaji", name = "Altbalaji", url = "https://prmovies.church/director/altbalaji/"),
        Category(id = "zee5", name = "Zee5", url = "https://prmovies.church/director/zee5/"),
        Category(id = "voot-originals", name = "Voot", url = "https://prmovies.church/director/voot-originals/"),
        Category(id = "mx-player", name = "Mx Player", url = "https://prmovies.church/director/mx-player/"),
        Category(id = "hotstar", name = "Hotstar", url = "https://prmovies.church/director/hotstar/"),
        Category(id = "viu-originals", name = "Viu", url = "https://prmovies.church/director/viu-originals/"),
        Category(id = "sonyliv-original", name = "Sony Liv", url = "https://prmovies.church/director/sonyliv-original/"),
        Category(id = "animation", name = "Animation", url = "https://prmovies.church/genre/animation/"),
        Category(id = "watchocartoon.com", name = "Cartoon Movies", url = "https://watchocartoon.com"),
        Category(id = "action", name = "Action", url = "https://prmovies.church/genre/action/"),
        Category(id = "adventure", name = "Adventure", url = "https://prmovies.church/genre/adventure/"),
        Category(id = "biography", name = "Biography", url = "https://prmovies.church/genre/biography/"),
        Category(id = "comedy", name = "Comedy", url = "https://prmovies.church/genre/comedy/"),
        Category(id = "crime", name = "Crime", url = "https://prmovies.church/genre/crime/"),
        Category(id = "drama", name = "Drama", url = "https://prmovies.church/genre/drama/"),
        Category(id = "music", name = "Music", url = "https://prmovies.church/genre/music/"),
        Category(id = "mystery", name = "Mystery", url = "https://prmovies.church/genre/mystery/"),
        Category(id = "family", name = "Family", url = "https://prmovies.church/genre/family/"),
        Category(id = "fantasy", name = "Fantasy", url = "https://prmovies.church/genre/fantasy/"),
        Category(id = "horror", name = "Horror", url = "https://prmovies.church/genre/horror/"),
        Category(id = "history", name = "History", url = "https://prmovies.church/genre/history/"),
        Category(id = "romantic", name = "Romance", url = "https://prmovies.church/genre/romantic/"),
        Category(id = "science-fiction", name = "Science Fiction", url = "https://prmovies.church/genre/science-fiction/"),
        Category(id = "thriller", name = "Thriller", url = "https://prmovies.church/genre/thriller/"),
        Category(id = "war", name = "War", url = "https://prmovies.church/genre/war/"),
        Category(id = "south-special", name = "ExtraMovies", url = "https://prmovies.church/genre/south-special/"),
        Category(id = "punjabimoviez.space", name = "Punjabi Movies", url = "https://punjabimoviez.space"),
        Category(id = "bengali", name = "Bengali", url = "https://prmovies.church/genre/bengali/"),
        Category(id = "marathi", name = "Marathi", url = "https://prmovies.church/genre/marathi/"),
        Category(id = "gujarati", name = "Gujarati", url = "https://prmovies.church/genre/gujarati/"),
        Category(id = "tamil", name = "Tamil", url = "https://prmovies.church/genre/tamil/"),
        Category(id = "telugu", name = "Telugu", url = "https://prmovies.church/genre/telugu/"),
        Category(id = "malayalam", name = "Malayalam", url = "https://prmovies.church/genre/malayalam/"),
        Category(id = "kannada", name = "Kannada", url = "https://prmovies.church/genre/kannada/"),
        Category(id = "pakistani", name = "Pakistani", url = "https://prmovies.church/genre/pakistani/"),
        Category(id = "erotic-movies", name = "Erotic", url = "https://prmovies.church/genre/erotic-movies/"),
        Category(id = "erotic-movies", name = "New Erotic", url = "https://watchoerotic.com/genre/erotic-movies/"),
        Category(id = "tv-shows", name = "Hot Series", url = "https://prmovies.church/genre/tv-shows/"),
        Category(id = "church_cat_57", name = "Ullu Originals", url = "https://prmovies.church/?s=ullu"),
        Category(id = "church_cat_58", name = "Uncut", url = "https://prmovies.church/?s=uncut"),
        Category(id = "fliz-movies", name = "Fliz Movies", url = "https://prmovies.church/director/fliz-movies/"),
        Category(id = "nuefliks-exclusive", name = "Nuefliks", url = "https://prmovies.church/director/nuefliks-exclusive/"),
        Category(id = "hotshots", name = "Hotshots", url = "https://prmovies.church/director/hotshots/"),
        Category(id = "hunters-originals", name = "Hunters", url = "https://prmovies.church/director/hunters-originals/"),
        Category(id = "moodx-originals", name = "MoodX", url = "https://prmovies.church/director/moodx-originals/"),
        Category(id = "voovi-originals", name = "VooVi", url = "https://prmovies.church/director/voovi-originals/"),
        Category(id = "primeplay-originals", name = "PrimePlay", url = "https://prmovies.church/director/primeplay-originals/"),
        Category(id = "besharams-originals", name = "Besharams", url = "https://prmovies.church/director/besharams-originals/"),
        Category(id = "kooku-originals", name = "Kooku", url = "https://prmovies.church/director/kooku-originals/"),
        Category(id = "gupchup-exclusive", name = "Gupchup", url = "https://prmovies.church/director/gupchup-exclusive/"),
        Category(id = "feneomovies", name = "Feneomovies", url = "https://prmovies.church/director/feneomovies/"),
        Category(id = "cinemadosti", name = "Cinemadosti", url = "https://prmovies.church/director/cinemadosti/"),
        Category(id = "primeflix", name = "Primeflix", url = "https://prmovies.church/director/primeflix/"),
        Category(id = "gemplex", name = "Gemplex", url = "https://hindilinks4u.energy/director/gemplex/"),
        Category(id = "rabbit-original", name = "Rabbit", url = "https://prmovies.mba/director/rabbit-original/"),
        Category(id = "hotmasti-originals", name = "HotMasti", url = "https://uwatchfree.cyou/director/hotmasti-originals/"),
        Category(id = "boommovies-original", name = "BoomMovies", url = "https://latestmovies.skin/director/boommovies-original/"),
        Category(id = "cliff-movies", name = "CliffMovies", url = "https://yomovies1.baby/director/cliff-movies/"),
        Category(id = "masti-prime-originals", name = "MastiPrime", url = "https://yomovies1.ink/director/masti-prime-originals/"),
        Category(id = "ek-night-show", name = "Ek Night Show", url = "https://watchofree.beauty/director/ek-night-show/"),
        Category(id = "flixsksmovies", name = "Flixsksmovies", url = "https://2umovies.study/director/flixsksmovies/"),
        Category(id = "lootlo-original", name = "Lootlo", url = "https://watchomovies.forum/director/lootlo-original/"),
        Category(id = "hootzy-channel", name = "Hootzy", url = "https://watchomovies.forum/director/hootzy-channel/"),
        Category(id = "balloons-originals", name = "Balloons", url = "https://gofilms4u.site/director/balloons-originals/"),
        Category(id = "big-movie-zoo-originals", name = "Big Movie Zoo", url = "https://yomovies.news/director/big-movie-zoo-originals/"),
        Category(id = "bambooflix", name = "Bambooflix", url = "https://prmovies.church/director/bambooflix/"),
        Category(id = "piliflix-originals", name = "Piliflix", url = "https://speedostream.email/director/piliflix-originals/"),
        Category(id = "11upmovies-originals", name = "11upmovies", url = "https://hindilinks4u.energy/director/11upmovies-originals/"),
        Category(id = "eightshots-originals", name = "Eightshots", url = "https://hindilinks4u.energy/director/eightshots-originals/"),
        Category(id = "i-entertainment-exclusive", name = "I-Entertainment", url = "https://gofilms4u.cam/director/i-entertainment-exclusive/"),
        Category(id = "hotprime-originals", name = "Hotprime", url = "https://hhdmovies.study/director/hotprime-originals/"),
        Category(id = "banana-prime", name = "BananaPrime", url = "https://filmlinks4u.guru/director/banana-prime/"),
        Category(id = "hothitfilms", name = "HotHitFilms", url = "https://yomovies.church/director/hothitfilms/"),
        Category(id = "worldprime-originals", name = "Worldprime", url = "https://2umovies.study/director/worldprime-originals/"),
        Category(id = "chikooflix-originals", name = "Chikooflix", url = "https://yomovies.church/director/chikooflix-originals/"),
        Category(id = "church_cat_94", name = "Glamheart", url = "https://yomovies.church/?s=glamheart"),
    )

    private val COM_CATEGORIES = listOf(
        Category(id = "com_cat_1", name = "Ullu", url = "https://prmovies.com/?s=ullu"),
        Category(id = "hotshots", name = "Hotshots", url = "https://prmovies.com/director/hotshots/"),
        Category(id = "fliz-movies", name = "Fliz", url = "https://prmovies.com/director/fliz-movies/"),
        Category(id = "nuefliks-exclusive", name = "Nuefliks", url = "https://prmovies.com/director/nuefliks-exclusive/"),
        Category(id = "cinemadosti", name = "Cinemadosti", url = "https://prmovies.com/director/cinemadosti/"),
        Category(id = "feneomovies", name = "Feneomovies", url = "https://prmovies.com/director/feneomovies/"),
        Category(id = "kooku-originals", name = "Kooku", url = "https://prmovies.com/director/kooku-originals/"),
        Category(id = "com_cat_8", name = "Glamheart", url = "https://prmovies.com/?s=glamheart"),
        Category(id = "gupchup-exclusive", name = "Gupchup", url = "https://prmovies.com/director/gupchup-exclusive/"),
        Category(id = "com_cat_10", name = "I Entertainment", url = "https://prmovies.com/?s=Entertainment"),
        Category(id = "com_cat_11", name = "EightShots", url = "https://prmovies.com/?s=EightShots"),
        Category(id = "com_cat_12", name = "BoltiKahani", url = "https://prmovies.com/?s=BoltiKahani"),
        Category(id = "com_cat_13", name = "BananaPrime", url = "https://prmovies.com/?s=Banana"),
        Category(id = "com_cat_14", name = "Kfilms", url = "https://prmovies.com/?s=Kfilms"),
        Category(id = "primeflix", name = "Primeflix", url = "https://prmovies.com/director/primeflix/"),
        Category(id = "11upmovies-originals", name = "11UpMovies", url = "https://prmovies.com/director/11upmovies-originals/"),
        Category(id = "ek-night-show", name = "Ek Night Show", url = "https://prmovies.com/director/ek-night-show/"),
        Category(id = "pulseprime-original", name = "PulsePrime", url = "https://prmovies.com/director/pulseprime-original/"),
        Category(id = "hootzy-channel", name = "Hootzy", url = "https://prmovies.com/director/hootzy-channel/"),
        Category(id = "hotmasti-originals", name = "HotMasti", url = "https://prmovies.com/director/hotmasti-originals/"),
        Category(id = "masti-prime-originals", name = "Masti Prime", url = "https://prmovies.com/director/masti-prime-originals/"),
        Category(id = "kindibox-original", name = "KindiBOX", url = "https://prmovies.com/director/kindibox-original/"),
        Category(id = "chikooflix-originals", name = "ChikooFlix", url = "https://prmovies.com/director/chikooflix-originals/"),
        Category(id = "electecity-exclusive", name = "ElectECity", url = "https://prmovies.com/director/electecity-exclusive/"),
        Category(id = "cliff-movies", name = "Cliff Movies", url = "https://prmovies.com/director/cliff-movies/"),
        Category(id = "netdik-exclusive", name = "Netdik", url = "https://prmovies.com/director/netdik-exclusive/"),
        Category(id = "hotvolt-originals", name = "HotVolt", url = "https://prmovies.com/director/hotvolt-originals/"),
        Category(id = "desivideoapp-exclusive", name = "DesiVideoApp", url = "https://prmovies.com/director/desivideoapp-exclusive/"),
        Category(id = "masti-movies", name = "Masti Movies", url = "https://prmovies.com/director/masti-movies/"),
        Category(id = "khirki-originals", name = "Khirki", url = "https://prmovies.com/director/khirki-originals/"),
        Category(id = "big-movie-zoo-originals", name = "Big Movie Zoo", url = "https://prmovies.com/director/big-movie-zoo-originals/"),
        Category(id = "com_cat_32", name = "JOLLU Exclusive", url = "https://prmovies.com/?s=jollu"),
        Category(id = "com_cat_33", name = "Poonam Pandey", url = "https://prmovies.com/?s=poonam"),
        Category(id = "com_cat_34", name = "Aabha Paul", url = "https://prmovies.com/?s=aabha"),
        Category(id = "com_cat_35", name = "Anveshi Jain", url = "https://prmovies.com/?s=anveshi"),
        Category(id = "com_cat_36", name = "Simran Kaur", url = "https://prmovies.com/?s=simran"),
        Category(id = "com_cat_37", name = "MahuaDatta", url = "https://prmovies.com/?s=mahua"),
        Category(id = "sapna-sappu", name = "Sapna Sappu", url = "https://prmovies.com/stars/sapna-sappu/"),
        Category(id = "dolon", name = "Dolon", url = "https://prmovies.com/stars/dolon/"),
        Category(id = "rupmita", name = "Rupmita", url = "https://prmovies.com/stars/rupmita/"),
        Category(id = "sunny-leone", name = "Sunny Leone", url = "https://prmovies.com/director/sunny-leone/"),
        Category(id = "aiysha-saagar", name = "Aiysha Saagar", url = "https://prmovies.com/director/aiysha-saagar/"),
        Category(id = "kavita-radheshyam", name = "Kavita Radheshyam", url = "https://prmovies.com/stars/kavita-radheshyam/"),
    )

    fun getCategories(providerId: String, activeBaseUrl: String): List<Category> {
        val base = activeBaseUrl.trimEnd('/')
        val list = if (providerId == "prmovies_church") CHURCH_CATEGORIES else COM_CATEGORIES
        return list.map { cat ->
            val targetUrl = if (providerId == "prmovies_church" && cat.url.contains("prmovies.church")) {
                cat.url.replace("https://prmovies.church", base)
            } else if (providerId == "prmovies" && cat.url.contains("prmovies.com")) {
                cat.url.replace("https://prmovies.com", base)
            } else cat.url
            cat.copy(url = targetUrl)
        }
    }
}
