package com.thedesitadka.app.ui.screens

data class FilterOption(val label: String, val value: String)

object PrmoviesFilterData {

    val SORT_OPTIONS = listOf(
        FilterOption("Latest", "latest"),
        FilterOption("Most Viewed", "most-viewed"),
        FilterOption("Most Favorite", "most-favorite"),
        FilterOption("Most Rating", "most-rating"),
        FilterOption("Top IMDb", "top-imdb"),
    )

    val QUALITIES = listOf(
        FilterOption("18+", "18"),
        FilterOption("720p", "720p"),
        FilterOption("Bengali", "bengali"),
        FilterOption("Bhojpuri", "bhojpuri"),
        FilterOption("Gujarati", "gujarati"),
        FilterOption("HINDI", "hindi"),
        FilterOption("Malayalam", "malayalam"),
        FilterOption("Marathi", "marathi"),
        FilterOption("Nepali", "nepali"),
        FilterOption("Pakistani", "pakistani"),
        FilterOption("Punjabi", "punjabi"),
        FilterOption("SD", "sd"),
        FilterOption("Tamil", "tamil"),
        FilterOption("Telugu", "telugu"),
    )

    val GENRES = listOf(
        FilterOption("18+", "18"),
        FilterOption("Action", "action"),
        FilterOption("Action & Adventure", "action-adventure"),
        FilterOption("AdultTime", "adulttime"),
        FilterOption("Adventure", "adventure"),
        FilterOption("Animation", "animation"),
        FilterOption("Asian", "asian"),
        FilterOption("Bengali", "bengali"),
        FilterOption("Bhojpuri", "bhojpuri"),
        FilterOption("Biography", "biography"),
        FilterOption("Bollywood", "bollywood"),
        FilterOption("Comedy", "comedy"),
        FilterOption("Crime", "crime"),
        FilterOption("Documentary", "documentary"),
        FilterOption("Drama", "drama"),
        FilterOption("Dual Audio", "dual-audio"),
        FilterOption("Erotic Movies", "erotic-movies"),
        FilterOption("Family", "family"),
        FilterOption("Fantasy", "fantasy"),
        FilterOption("Foreign", "foreign"),
        FilterOption("Gujarati", "gujarati"),
        FilterOption("History", "history"),
        FilterOption("Hollywood", "hollywood"),
        FilterOption("Hollywood Dubbed", "hollywood-dubbed"),
        FilterOption("Horror", "horror"),
        FilterOption("Kannada", "kannada"),
        FilterOption("Kids", "kids"),
        FilterOption("Korean", "korean"),
        FilterOption("Latest Added", "latest-added"),
        FilterOption("Malayalam", "malayalam"),
        FilterOption("Marathi", "marathi"),
        FilterOption("Music", "music"),
        FilterOption("Musical", "musical"),
        FilterOption("Mystery", "mystery"),
        FilterOption("Nepali", "nepali"),
        FilterOption("news", "news"),
        FilterOption("Pakistani", "pakistani"),
        FilterOption("Psychological", "psychological"),
        FilterOption("Punjabi", "punjabi"),
        FilterOption("Reality", "reality"),
        FilterOption("Romance", "romantic"),
        FilterOption("Sci-fi", "sci-fi"),
        FilterOption("Sci-Fi & Fantasy", "sci-fi-fantasy"),
        FilterOption("Science Fiction", "science-fiction"),
        FilterOption("Short", "short"),
        FilterOption("Slider", "slider"),
        FilterOption("South Special", "south-special"),
        FilterOption("Sport", "sport"),
        FilterOption("Talk", "talk"),
        FilterOption("Tamil", "tamil"),
        FilterOption("Telugu", "telugu"),
        FilterOption("Thriller", "thriller"),
        FilterOption("Top Rated", "top-rated"),
        FilterOption("TV Movie", "tv-movie"),
        FilterOption("TV Shows", "tv-shows"),
        FilterOption("Unofficial Dubbed", "unofficial-dubbed"),
        FilterOption("War", "war"),
        FilterOption("War & Politics", "war-politics"),
        FilterOption("Web Series", "web-series"),
        FilterOption("western", "western"),
    )

    val COUNTRIES = listOf(
        FilterOption("2026", "2026"),
        FilterOption("Afghanistan", "afghanistan"),
        FilterOption("Albania", "albania"),
        FilterOption("Algeria", "algeria"),
        FilterOption("Amazon Prime", "amazon-prime"),
        FilterOption("Andorra", "andorra"),
        FilterOption("Angola", "angola"),
        FilterOption("Antarctica", "antarctica"),
        FilterOption("Argentina", "argentina"),
        FilterOption("Armenia", "armenia"),
        FilterOption("Aruba", "aruba"),
        FilterOption("Australia", "australia"),
        FilterOption("Austria", "austria"),
        FilterOption("Azerbaijan", "azerbaijan"),
        FilterOption("Bahamas", "bahamas"),
        FilterOption("Bahrain", "bahrain"),
        FilterOption("Bangladesh", "bangladesh"),
        FilterOption("Barbados", "barbados"),
        FilterOption("Belarus", "belarus"),
        FilterOption("Belgium", "belgium"),
        FilterOption("Belize", "belize"),
        FilterOption("Bermuda", "bermuda"),
        FilterOption("Bhutan", "bhutan"),
        FilterOption("Bolivia", "bolivia"),
        FilterOption("Bosnia and Herzegovina", "bosnia-and-herzegovina"),
        FilterOption("Botswana", "botswana"),
        FilterOption("Brazil", "brazil"),
        FilterOption("British Virgin Islands", "british-virgin-islands"),
        FilterOption("Bulgaria", "bulgaria"),
        FilterOption("Cambodia", "cambodia"),
        FilterOption("Cameroon", "cameroon"),
        FilterOption("Canada", "canada"),
        FilterOption("Cayman Islands", "cayman-islands"),
        FilterOption("Chad", "chad"),
        FilterOption("Chile", "chile"),
        FilterOption("China", "china"),
        FilterOption("Colombia", "colombia"),
        FilterOption("Congo", "congo"),
        FilterOption("Costa Rica", "costa-rica"),
        FilterOption("Côte d'Ivoire", "cote-divoire"),
        FilterOption("Croatia", "croatia"),
        FilterOption("Cuba", "cuba"),
        FilterOption("Cyprus", "cyprus"),
        FilterOption("Czech Republic", "czech-republic"),
        FilterOption("Denmark", "denmark"),
        FilterOption("Dominican Republic", "dominican-republic"),
        FilterOption("East Germany", "east-germany"),
        FilterOption("Ecuador", "ecuador"),
        FilterOption("Egypt", "egypt"),
        FilterOption("El Salvador", "el-salvador"),
        FilterOption("Estonia", "estonia"),
        FilterOption("Ethiopia", "ethiopia"),
        FilterOption("Federal Republic of Yugoslavia", "federal-republic-of-yugoslavia"),
        FilterOption("Feodor Chin", "feodor-chin"),
        FilterOption("Fiji", "fiji"),
        FilterOption("Finland", "finland"),
        FilterOption("France", "france"),
        FilterOption("French Polynesia", "french-polynesia"),
        FilterOption("Georgia", "georgia"),
        FilterOption("Germany", "germany"),
        FilterOption("Ghana", "ghana"),
        FilterOption("Greece", "greece"),
        FilterOption("Guadeloupe", "guadeloupe"),
        FilterOption("Guatemala", "guatemala"),
        FilterOption("Haiti", "haiti"),
        FilterOption("Han Ji-minPark Sung-hoonLee Ki-taek", "han-ji-minpark-sung-hoonlee-ki-taek"),
        FilterOption("Holy See (Vatican City State)", "holy-see-vatican-city-state"),
        FilterOption("Honduras", "honduras"),
        FilterOption("Hong Kong", "hong-kong"),
        FilterOption("Hungary", "hungary"),
        FilterOption("Iceland", "iceland"),
        FilterOption("India", "india"),
        FilterOption("Indonesia", "indonesia"),
        FilterOption("International", "international"),
        FilterOption("Iran", "iran"),
        FilterOption("Iraq", "iraq"),
        FilterOption("Ireland", "ireland"),
        FilterOption("Isle Of Man", "isle-of-man"),
        FilterOption("Israel", "israel"),
        FilterOption("Istanbul", "istanbul"),
        FilterOption("Italy", "italy"),
        FilterOption("Jamaica", "jamaica"),
        FilterOption("Japan", "japan"),
        FilterOption("Jordan", "jordan"),
        FilterOption("Jung Hae-In", "jung-hae-in"),
        FilterOption("Kamalika Chanda", "kamalika-chanda"),
        FilterOption("Kazakhstan", "kazakhstan"),
        FilterOption("Kenya", "kenya"),
        FilterOption("Korea", "korea"),
        FilterOption("Kosovo", "kosovo"),
        FilterOption("Kuwait", "kuwait"),
        FilterOption("Kyrgyzstan", "kyrgyzstan"),
        FilterOption("Latvia", "latvia"),
        FilterOption("Lebanon", "lebanon"),
        FilterOption("Liberia", "liberia"),
        FilterOption("Libya", "libya"),
        FilterOption("Liechtenstein", "liechtenstein"),
        FilterOption("Lithuania", "lithuania"),
        FilterOption("Luxembourg", "luxembourg"),
        FilterOption("Macao", "macao"),
        FilterOption("Madagascar", "madagascar"),
        FilterOption("Malaysia", "malaysia"),
        FilterOption("Maldives", "maldives"),
        FilterOption("Malta", "malta"),
        FilterOption("Mauritania", "mauritania"),
        FilterOption("Mauritius", "mauritius"),
        FilterOption("Mexico", "mexico"),
        FilterOption("Micronesia", "micronesia"),
        FilterOption("Moldova", "moldova"),
        FilterOption("Monaco", "monaco"),
        FilterOption("Mongolia", "mongolia"),
        FilterOption("Montenegro", "montenegro"),
        FilterOption("Morocco", "morocco"),
        FilterOption("Mozambique", "mozambique"),
        FilterOption("Myanmar", "myanmar"),
        FilterOption("N/A", "n-a"),
        FilterOption("Namibia", "namibia"),
        FilterOption("Nepal", "nepal"),
        FilterOption("Netherlands", "netherlands"),
        FilterOption("Netherlands Antilles", "netherlands-antilles"),
        FilterOption("New Zealand", "new-zealand"),
        FilterOption("Nigeria", "nigeria"),
        FilterOption("North Korea", "north-korea"),
        FilterOption("Norway", "norway"),
        FilterOption("Pakistan", "pakistan"),
        FilterOption("Palau", "palau"),
        FilterOption("Palestine", "palestine"),
        FilterOption("Panama", "panama"),
        FilterOption("Papua New Guinea", "papua-new-guinea"),
        FilterOption("Paraguay", "paraguay"),
        FilterOption("Peru", "peru"),
        FilterOption("Philippines", "philippines"),
        FilterOption("Poland", "poland"),
        FilterOption("Portugal", "portugal"),
        FilterOption("Puerto Rico", "puerto-rico"),
        FilterOption("Qatar", "qatar"),
        FilterOption("Republic of Macedonia", "republic-of-macedonia"),
        FilterOption("Republic of North Macedonia", "republic-of-north-macedonia"),
        FilterOption("Romania", "romania"),
        FilterOption("Russia", "russia"),
        FilterOption("Rwanda", "rwanda"),
        FilterOption("Saint Helena", "saint-helena"),
        FilterOption("Saint Kitts and Nevis", "saint-kitts-and-nevis"),
        FilterOption("Samoa", "samoa"),
        FilterOption("Sana Khan", "sana-khan"),
        FilterOption("Saudi Arabia", "saudi-arabia"),
        FilterOption("Senegal", "senegal"),
        FilterOption("Seong-gyoon Kim", "seong-gyoon-kim"),
        FilterOption("Serbia", "serbia"),
        FilterOption("Serbia and Montenegro", "serbia-and-montenegro"),
        FilterOption("Sierra Leone", "sierra-leone"),
        FilterOption("Singapore", "singapore"),
        FilterOption("Slovakia", "slovakia"),
        FilterOption("Slovenia", "slovenia"),
        FilterOption("South Africa", "south-africa"),
        FilterOption("South Korea", "south-korea"),
        FilterOption("Soviet Union", "soviet-union"),
        FilterOption("Spain", "spain"),
        FilterOption("Sri Lanka", "sri-lanka"),
        FilterOption("Sweden", "sweden"),
        FilterOption("Switzerland", "switzerland"),
        FilterOption("Syria", "syria"),
        FilterOption("Taiwan", "taiwan"),
        FilterOption("Tajikistan", "tajikistan"),
        FilterOption("Tanzania", "tanzania"),
        FilterOption("Thailand", "thailand"),
        FilterOption("The Democratic Republic Of Congo", "the-democratic-republic-of-congo"),
        FilterOption("Trinidad and Tobago", "trinidad-and-tobago"),
        FilterOption("Tripti Berra", "tripti-berra"),
        FilterOption("Tunisia", "tunisia"),
        FilterOption("Turkey", "turkey"),
        FilterOption("Uganda", "uganda"),
        FilterOption("UK", "uk"),
        FilterOption("Ukraine", "ukraine"),
        FilterOption("United Arab Emirates", "united-arab-emirates"),
        FilterOption("United Kingdom", "united-kingdom"),
        FilterOption("United States", "united-states"),
        FilterOption("Uruguay", "uruguay"),
        FilterOption("USA", "usa"),
        FilterOption("Uzbekistan", "uzbekistan"),
        FilterOption("Vanuatu", "vanuatu"),
        FilterOption("Venezuela", "venezuela"),
        FilterOption("Vietnam", "vietnam"),
        FilterOption("West Germany", "west-germany"),
        FilterOption("Yemen", "yemen"),
        FilterOption("Yugoslavia", "yugoslavia"),
        FilterOption("Zambia", "zambia"),
        FilterOption("Zimbabwe", "zimbabwe"),
    )

    val YEARS = listOf(
        FilterOption("1915", "1915"),
        FilterOption("1916", "1916"),
        FilterOption("1919", "1919"),
        FilterOption("1921", "1921"),
        FilterOption("1925", "1925"),
        FilterOption("1926", "1926"),
        FilterOption("1927", "1927"),
        FilterOption("1928", "1928"),
        FilterOption("1929", "1929"),
        FilterOption("1931", "1931"),
        FilterOption("1932", "1932"),
        FilterOption("1933", "1933"),
        FilterOption("1936", "1936"),
        FilterOption("1937", "1937"),
        FilterOption("1938", "1938"),
        FilterOption("1939", "1939"),
        FilterOption("1940", "1940"),
        FilterOption("1941", "1941"),
        FilterOption("1942", "1942"),
        FilterOption("1943", "1943"),
        FilterOption("1944", "1944"),
        FilterOption("1945", "1945"),
        FilterOption("1946", "1946"),
        FilterOption("1947", "1947"),
        FilterOption("1948", "1948"),
        FilterOption("1949", "1949"),
        FilterOption("1950", "1950"),
        FilterOption("1951", "1951"),
        FilterOption("1952", "1952"),
        FilterOption("1953", "1953"),
        FilterOption("1954", "1954"),
        FilterOption("1955", "1955"),
        FilterOption("1956", "1956"),
        FilterOption("1957", "1957"),
        FilterOption("1958", "1958"),
        FilterOption("1959", "1959"),
        FilterOption("1960", "1960"),
        FilterOption("1961", "1961"),
        FilterOption("1962", "1962"),
        FilterOption("1963", "1963"),
        FilterOption("1964", "1964"),
        FilterOption("1965", "1965"),
        FilterOption("1966", "1966"),
        FilterOption("1967", "1967"),
        FilterOption("1968", "1968"),
        FilterOption("1969", "1969"),
        FilterOption("1970", "1970"),
        FilterOption("1971", "1971"),
        FilterOption("1972", "1972"),
        FilterOption("1973", "1973"),
        FilterOption("1974", "1974"),
        FilterOption("1975", "1975"),
        FilterOption("1976", "1976"),
        FilterOption("1977", "1977"),
        FilterOption("1978", "1978"),
        FilterOption("1979", "1979"),
        FilterOption("1980", "1980"),
        FilterOption("1981", "1981"),
        FilterOption("1982", "1982"),
        FilterOption("1983", "1983"),
        FilterOption("1984", "1984"),
        FilterOption("1985", "1985"),
        FilterOption("1986", "1986"),
        FilterOption("1987", "1987"),
        FilterOption("1988", "1988"),
        FilterOption("1989", "1989"),
        FilterOption("1990", "1990"),
        FilterOption("1991", "1991"),
        FilterOption("1992", "1992"),
        FilterOption("1993", "1993"),
        FilterOption("1994", "1994"),
        FilterOption("1995", "1995"),
        FilterOption("1996", "1996"),
        FilterOption("1997", "1997"),
        FilterOption("1998", "1998"),
        FilterOption("1999", "1999"),
        FilterOption("2000", "2000"),
        FilterOption("2001", "2001"),
        FilterOption("2002", "2002"),
        FilterOption("2003", "2003"),
        FilterOption("2004", "2004"),
        FilterOption("2005", "2005"),
        FilterOption("2006", "2006"),
        FilterOption("2007", "2007"),
        FilterOption("2008", "2008"),
        FilterOption("2009", "2009"),
        FilterOption("2010", "2010"),
        FilterOption("2011", "2011"),
        FilterOption("2012", "2012"),
        FilterOption("2013", "2013"),
        FilterOption("2014", "2014"),
        FilterOption("2015", "2015"),
        FilterOption("2016", "2016"),
        FilterOption("2017", "2017"),
        FilterOption("2018", "2018"),
        FilterOption("2019", "2019"),
        FilterOption("202", "202"),
        FilterOption("2020", "2020"),
        FilterOption("2021", "2021"),
        FilterOption("2022", "2022"),
        FilterOption("2023", "2023"),
        FilterOption("2024", "2024"),
        FilterOption("2025", "2025"),
        FilterOption("2026", "2026"),
        FilterOption("USA", "usa"),
    )
}
